# ────────────────────────────────────────────────────────────────
#  Database Systems - Common Docker Setup
#
#  Quick summary of what this file accomplishes
#
#    * Defines two containers that work together
#      - db: a PostgreSQL database
#      - pgadmin: a web interface to manage the PostgreSQL db
#      - mongodb: a MongoDB database
#    * They share a network so they can communicate.
#    * A "container" is a disposible unit so, db, mongodb,
#      and pgadmin each have volumes that map to your
#      computer so their data persists even if they
#      are destroyed.
#    * The ports lines expose db and pgadmin to your computer.
#      - db → localhost:5432
#      - pgAdmin → localhost:5050
#      - mongodb → localhost:27017
#
#  Commands you will want to use:
#    * Launch both containers     : docker compose up -d
#    * Shut down both containers  : docker compose down -v
#    * Work w/ postgres using CLI : docker exec -it dbcontainer psql -U student -d mydb
#    * Work w/ postgres using Web : Visit: http://localhost:5050
#    * Work w/ mongo using CLI    : docker exec -it mongocontainer mongosh -u mongo -p mongo
# ────────────────────────────────────────────────────────────────
services:
  db:
    image: postgres:16
    container_name: dbcontainer
    restart: unless-stopped
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmincontainer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: student@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongodb:
    image: mongo:7
    container_name: mongocontainer
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - db-net

networks:
  db-net:
    external: true

volumes:
  pgdata:
    external: true
  pgadmin-data:
    external: true
  mongodata:
    external: true

